server:
  port: 8770

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: service-feign
#feign自带断路器 需要手动开启
feign:
  hystrix:
    enabled: true